---
title: "ベータ分布"
author: "@anemptyarchive\\thanks{\\url{https://www.anarchive-beta.com/}}"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  pdf_document:
    latex_engine: xelatex
    number_section: true
    toc: true
    toc_depth: 4
    keep_tex: false
header-includes:
  - \usepackage{bookmark}
  - \usepackage{xltxtra}
  - \usepackage{zxjatype}
  - \usepackage[ipa]{zxjafont}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, error = FALSE, warning = FALSE, # メッセージを非表示
  fig.align = "center", # 画像を中央揃え
  fig.width = 6, fig.height = 4.5, # 画像のサイズ
  dev = "cairo_pdf", dev.args = list(family = "ipaexg"), # {ggplot2}に日本語を組み込む場合の対処
  class.source = "numberLines lineAnchors", # ソースを番号付けする
  class.output = "numberLines lineAnchors chunkout" # 出力を番号付けする
)
```

----

【編集履歴】

- 2022/01/15：執筆開始
- 2022/00/00：中断

----

\newpage


# ベータ分布の定義式

　ベータ分布(Beta Distribution)の定義を確認します。\
\


## 定義式

　ベータ分布とは、ベルヌーイ分布・二項分布のパラメータ$0 \leq \phi \leq 1$を生成するための確率分布である。このような分布を共役事前分布と呼ぶ。\
\

　ベータ分布は次の式で定義される。

$$
\mathrm{Beta}(\phi | \alpha, \beta)
  = \frac{
        \Gamma(\alpha + \beta)
    }{
        \Gamma(\alpha) \Gamma(\beta)
    }
    \phi^{\alpha-1}
    (1 - \phi)^{\beta-1}
\tag{1.8}
$$

　ここで$\alpha,\ \beta$はベータ分布のパラメータであり、次の条件を満たす必要がある。

$$
\alpha > 0,\ 
\beta > 0
$$

　共役事前分布のパラメータのことをハイパーパラメータとも呼ぶ。\

　この式に従うと、ベルヌーイ分布・二項分布のパラメータ$\phi,\ 1 - \phi$を求めることができる。\
\

　まずは、$\phi$の関数である$\phi^{\alpha-1} (1 - \phi)^{\beta-1}$について考える。\
　この関数を確率分布(確率密度関数)として扱うためには、全ての事象を考慮した際の値が1となる必要がある。しかしこの式のままではそうはならない。そこで、正規化項(この式の逆数となる値)$\frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}$を掛けることで対応する。\
\


## 他の分布との関係



## 統計量の計算式

　ベータ分布の平均と分散は、次の式で計算できます。詳しくは「統計量の導出」を参照してください。

$$
\begin{aligned}
\mathbb{E}[]
   &= 
\\
\mathbb{V}[]
   &= 
\end{aligned}
$$



# ベータ分布の正規化項の導出

　ベータ分布(Beta Distribution)の正規化項を導出します。\
\

　ベータ分布は、ベータ関数を用いて次の式で定義されます。

$$
\mathrm{Beta}(\phi | \alpha, \beta)
    = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \phi^{\alpha-1}
      (1 - \phi)^{\beta-1}
$$

　ベータ関数は、次の式で定義されます。

$$
B(\alpha,\beta)
    = \int_0^1
          x^{\alpha-1}
          (1 - x)^{\beta-1}
      dx
$$

　部分積分$\int_a^b f'(x) g(x) dx = [f(x) g(x)]_a^b - \int_a^b f(x) g'(x) dx$を行うために、前の項を

$$
x^{\alpha-1}
    = \left\{
          \int x^{\alpha-1} dx
      \right\}'
    = \left\{
          \frac{1}{\alpha}
          x^{\alpha}
      \right\}'
$$

と変形します。

$$
B(\alpha, \beta)
    = \int_0^1
          \left\{
              \frac{1}{\alpha}
              x^{\alpha}
      \right\}'
          (1 - x)^{\beta-1}
      dx
$$

　$f(x) = \frac{1}{\alpha} x^{\alpha}$、$f'(x) = \{ \frac{1}{\alpha} x^{\alpha} \}' = x^{\alpha-1}$を、$g(x) = (1 - x)^{\beta-1}$、$g'(x) = \{ (1 - x)^{\beta-1} \}' = - (\beta - 1) (1 - x)^{\beta-2}$として、部分積分を行います。$(1 - x)^{\beta-1}$については、合成関数の微分$\{g(f(x))\} = g'(f(x)) f'(x)$より

$$
\begin{aligned}
\{(1 - x)^{\beta-1}\}'
   &= (\beta - 1) (1 - x)^{\beta-2}
      (1 - x)'
\\
   &= (\beta - 1) (1 - x)^{\beta-2}
      (- 1)
\\
   &= - (\beta - 1) (1 - x)^{\beta-2}
\end{aligned}
$$

です。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \left[
          \frac{1}{\alpha} x^{\alpha}
          (1 - x)^{\beta-1}
      \right]_0^1
      - \int_0^1
          \frac{1}{\alpha} x^{\alpha}
          \Bigl\{
              - (\beta - 1) (1 - x)^{\beta-2}
          \Bigr\}
        dx
\\
   &= \left[
          \frac{1}{\alpha} x^{\alpha}
          (1 - x)^{\beta-1}
      \right]_0^1
      + \frac{\beta - 1}{\alpha}
        \int_0^1
          x^{\alpha}
          (1 - x)^{\beta-2}
        dx
\end{aligned}
$$

　前の因子について、定積分$\int_a^b f(x) dx = [F(x)]_a^b = F(b) - F(a)$を行うと、0になり消えます。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \frac{1}{\alpha} 0^{\alpha}
      (1 - 0)^{\beta-1}
      - \frac{1}{\alpha} 1^{\alpha}
      (1 - 1)^{\beta-1}
      + \frac{\beta - 1}{\alpha}
        \int_0^1
          x^{\alpha}
          (1 - x)^{\beta-2}
        dx
\\
   &= 0 - 0
      + \frac{\beta - 1}{\alpha}
        \int_0^1
          x^{\alpha}
          (1 - x)^{\beta-2}
        dx
\end{aligned}
$$

　後の因子について、ベータ関数の定義より置き換えます。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \frac{\beta - 1}{\alpha}
      \int_0^1
          x^{(\alpha+1)-1}
          (1 - x)^{(\beta-1)-1}
      dx
\\
   &= \frac{\beta - 1}{\alpha}
      B(\alpha + 1, \beta - 1)
\end{aligned}
$$

　$B(\alpha, \beta) = \frac{\beta - 1}{\alpha} B(\alpha + 1, \beta - 1)$になることから、$B(\alpha + 1, \beta - 1) = \frac{\beta - 2}{\alpha + 1} B(\alpha + 2, \beta - 2)$になります。

$$
B(\alpha, \beta)
    = \frac{\beta - 1}{\alpha}
      \frac{\beta - 2}{\alpha + 1}
      B(\alpha + 2, \beta - 2)
$$

　同様に、合計$\beta - 1$回繰り返します。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \frac{\beta - 1}{\alpha}
      \frac{\beta - 2}{\alpha + 1}
      \cdots
      \frac{\beta - (\beta - 2)}{\alpha + \beta - 3}
      \frac{\beta - (\beta - 1)}{\alpha + \beta - 2}
      B(\alpha + \beta - 1, \beta - (\beta - 1))
\\
   &= \frac{\beta - 1}{\alpha}
      \frac{\beta - 2}{\alpha + 1}
      \cdots
      \frac{2}{\alpha + \beta - 3}
      \frac{1}{\alpha + \beta - 2}
      B(\alpha + \beta - 1, 1)
\end{aligned}
$$

　分子は、1から$\beta - 1$までの自然数の積なので、$\beta - 1$の階乗$(\beta - 1)!$です。分母は、$\alpha$から$\alpha + \beta - 2$までの自然数の積なので、分母分子に$(\alpha - 1)!$を掛けると$(\alpha + \beta - 2)!$になります。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \frac{
         (\beta - 1) (\beta - 2) \cdots 1
      }{
          \alpha (\alpha + 1) \cdots (\alpha + \beta - 2)
      }
      B(\alpha + \beta - 1, 1)
\\
   &= \frac{
         (\beta - 1)! (\alpha - 1)!
      }{
          (\alpha + \beta - 2)!
      }
      B(\alpha + \beta - 1, 1)
\end{aligned}
$$

　最後の項について、定積分を行うと

$$
\begin{aligned}
B(\alpha + \beta - 1, 1)
   &= \int_0^1
          x^{\alpha+\beta-1-1}
          (1 - x)^{1-1}
      dx
\\
   &= \left[
          \frac{1}{\alpha + \beta - 1}
          x^{\alpha+\beta-1}
      \right]_0^1
\\
   &= \frac{1}{\alpha + \beta - 1}
      1^{\alpha+\beta-1}
      + \frac{1}{\alpha + \beta - 1}
        0^{\alpha+\beta-1}
\\
   &= \frac{1}{\alpha + \beta - 1}
\end{aligned}
$$

となります。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \frac{
         (\beta - 1)! (\alpha - 1)!
      }{
          (\alpha + \beta - 2)!
      }
      \frac{1}{\alpha + \beta - 1}
\\
   &= \frac{
          (\alpha - 1)! (\beta - 1)!
      }{
          (\alpha + \beta - 1)!
      }
\end{aligned}
$$

　ガンマ関数の性質$\Gamma(x) = (x - 1)!$より、各項を置き換えます。

$$
B(\alpha, \beta)
    = \frac{\Gamma(\alpha) \Gamma(\beta)}{\Gamma(\alpha + \beta)}
$$

　ベータ関数$B(\alpha,\beta) = \frac{\Gamma(\alpha) \Gamma(\beta)}{\Gamma(\alpha + \beta)}$が求まった。この式の逆数$\frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}$を正規化項(積分して1とするための項)として用いることで、ベータ分布(1.8)が定義される。\
\



# ベータ分布の統計量の導出

　ベータ分布(Beta Distribution)の統計量を導出します。ベータ分布については「定義式の確認」を参照してください。\
\


## 定義式から導出

　定義式を利用して、平均・分散・最頻値の計算式を導出します。\

　ベータ分布は、次の式で定義されます。

$$
\mathrm{p}()
    = 
$$


### 平均の計算

　分布が取り得る値$\phi$とその確率密度$p(\phi)$を掛けて、0から1の範囲で積分した値が平均となる。

$$
\begin{aligned}
\mathbb{E}[\phi]
   &= \int_0^1
          \phi
          \mathrm{Beta}(\phi | \alpha, \beta)
      d\phi
\\
   &= \int_0^1
          \phi
          \frac{
              \Gamma(\alpha + \beta)
          }{
              \Gamma(\alpha) \Gamma(\beta)
          }
          \phi^{\alpha-1}
          (1 - \phi)^{\beta-1}
      d\phi
\end{aligned}
$$

1. 正規化項はベータ関数の逆数であるため、$\frac{1}{B(\alpha, \beta)} = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}$で置き換える。また$\phi \phi^{\alpha-1} = \phi^\alpha$で$\phi$の項をまとめる。


$$
\mathbb{E}[\phi]
    = \int_0^1
          \frac{1}{B(\alpha, \beta)}
          \phi^{\alpha}
          (1 - \phi)^{\beta-1}
      d\phi
$$

　$\alpha = \alpha' - 1$とおきます。

$$
\mathbb{E}[\phi]
    = \int_0^1
          \frac{1}{B(\alpha' - 1, \beta)}
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
$$


1. ベータ関数の定義式$B(\alpha, \beta) = \frac{\Gamma(\alpha) \Gamma(\beta)}{\Gamma(\alpha + \beta)} = \frac{(\alpha - 1)! (\beta - 1)!}{(\alpha + \beta - 1)!}$用いて、項を変形する。

　ベータ関数の定義式

$$
B(\alpha, \beta)
    = \frac{(\alpha - 1)! (\beta - 1)!}{(\alpha + \beta - 1)!}
$$

より、$B(\alpha - 1, \beta)$は

$$
B(\alpha - 1, \beta)
    = \frac{
          (\alpha - 2)! (\beta - 1)!
      }{
          (\alpha + \beta - 2)!
      }
$$

となる。この式の両辺に$\frac{\alpha - 1}{\alpha + \beta - 1}$を掛けると

$$
\begin{aligned}
\frac{\alpha - 1}{\alpha + \beta - 1}
B(\alpha - 1,\beta)
   &= \frac{
          (\alpha - 1) (\alpha - 2)! (\beta - 1)!
      }{
          (\alpha + \beta - 1) (\alpha + \beta - 2)!
      }
\\
   &= \frac{
          (\alpha - 1)! (\beta - 1)!
      }{
          (\alpha + \beta - 1)!
      }
    = B(\alpha, \beta)
\end{aligned}
$$

$B(\alpha, \beta)$となる。この式の両辺の逆数をとり、式を整理すると

$$
\frac{1}{B(\alpha - 1, \beta)}
  = \frac{\alpha - 1}{\alpha + \beta-1}
    \frac{1}{B(\alpha, \beta)}
$$

の関係が求まる。


5. 定数の項を$\int$の外に出す。また$\frac{1}{B(\alpha' - 1, \beta)}$を正規化項の形に戻す。
6. パラメータが$\alpha',\ \beta$のベータ分布について、
$\phi$が取り得る全ての値の積分であるため1になる。


$$
\begin{aligned}
\mathbb{E}[\phi]
   &= \int_0^1
          \frac{\alpha' - 1}{\alpha' + \beta - 1}
          \frac{1}{B(\alpha', \beta)}
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \frac{\alpha' - 1}{\alpha' + \beta - 1}
      \int_0^1
          \frac{
              \Gamma(\alpha' + \beta)
          }{
              \Gamma(\alpha') \Gamma(\beta)
          }
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \frac{\alpha' - 1}{\alpha' + \beta-1} * 1
\end{aligned}
$$

　$\alpha' = \alpha + 1$に戻します。

$$
\mathbb{E}[\phi]
    = \frac{\alpha}{\alpha + \beta}
$$

　平均の計算式が得られました。\
\


### 分散の計算

　「$\phi$の2乗の平均」と「$\phi$の平均の2乗」との差が分散となる。そこでまずは、$\phi$の2乗の平均を求める。

$$
\begin{aligned}
\mathbb{E}[\phi^2]
   &= \int_0^1 \phi^2 p(\phi) d\phi
\\
   &= \int_0^1
          \phi^2
          \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
          \phi^{\alpha-1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \int_0^1
          \frac{1}{B(\alpha, \beta)}
          \phi^{\alpha+1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \int_0^1
          \frac{1}{B(\alpha' - 2, \beta)}
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \int_0^1
          \frac{
              (\alpha' - 2) (\alpha' - 1)
          }{
              (\alpha' + \beta - 2) (\alpha' + \beta - 1)
          }
          \frac{1}{B(\alpha', \beta)}
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \frac{
          (\alpha' - 2) (\alpha' - 1)
      }{
          (\alpha' + \beta - 2) (\alpha' + \beta - 1)
      }
      \int_0^1
          \frac{\Gamma(\alpha' + \beta)}{\Gamma(\alpha') \Gamma(\beta)}
          \phi^{\alpha'-1} (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \frac{
          (\alpha' - 2) (\alpha' - 1)
      }{
          (\alpha' + \beta - 2) (\alpha' + \beta - 1)
      }
      * 1
\\
   &= \frac{
          \alpha (\alpha + 1)
      }{
          (\alpha + \beta)
          (\alpha + \beta + 1)
      }
\end{aligned}
$$

\begin{center}\underline{\hspace{10cm}}\end{center}

【途中式の途中式】

0. 平均の定義式(1.5')より、式を立てる。
1. $p(\phi) = \mathrm{Beta}(\phi | \alpha, \beta)$で置き換える。
1. 正規化項はベータ関数の逆数なので、$\frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)} = \frac{1}{B(\alpha, \beta)}$で置き換える。また$\phi^2  \phi^{\alpha-1} = \phi^{\alpha+1}$である。
1. $\alpha + 1 = \alpha' - 1$とおく。
1. ベータ関数の定義式$B(\alpha, \beta) = \frac{\Gamma(\alpha) \Gamma(\beta)}{\Gamma(\alpha + \beta)} = \frac{(\alpha - 1)! (\beta - 1)!}{(\alpha + \beta - 1)!}$を用いて、項を置き換える。

　先ほどと同様に、ベータ関数の定義式から

$$
\frac{
    (\alpha - 1) (\alpha - 2)
}{
    (\alpha + \beta - 1)
    (\alpha + \beta - 2)
}
B(\alpha - 2, \beta)
  = \frac{
        (\alpha - 1) (\alpha - 2)
    }{
        (\alpha + \beta - 1)
        (\alpha + \beta - 2)
    }
    \frac{
        (\alpha - 3)! (\beta - 1)!
    }{
        (\alpha + \beta - 3)!
    }
      = B(\alpha, \beta)
$$

となることが分かる。この式の両辺の逆数をとり、式を整理すると

$$
\frac{1}{B(\alpha - 2, \beta)}
    = \frac{
          (\alpha - 1) (\alpha - 2)
      }{
          (\alpha + \beta - 1)
          (\alpha + \beta - 2)
      }
      \frac{1}{B(\alpha, \beta)}
$$

の関係が求まる。

5. 定数の項を$\int$の外に出す。また$\frac{1}{B(\alpha', \beta)}$を正規化項の形に戻す。
6. パラメータが$\alpha',\ \beta$のベータ分布について、$0 \leq \phi \leq 1$の範囲での積分なので1になる。
7. $\alpha' = \alpha + 2$に戻す。

\begin{center}\underline{\hspace{10cm}}\end{center}

\ 

　「$\phi$の2乗の平均」と「$\phi$の平均の2乗」との差を求める。

$$
\begin{aligned}
\mathrm{Var}[\phi]
   &= \mathbb{E}[\phi^2]
      - (\mathbb{E}[\phi])^2
\\
   &= \frac{
          \alpha (\alpha + 1)
      }{
          (\alpha + \beta)
          (\alpha + \beta+1)
      }
      - \left(
            \frac{\alpha}{\alpha + \beta}
      \right)^2
\\
   &= \frac{
          \alpha (\alpha + 1) * (\alpha + \beta)
      }{
          (\alpha + \beta) (\alpha + \beta+1) * (\alpha + \beta)
      }
      - \frac{
            \alpha^2 * (\alpha + \beta+1)
        }{
            (\alpha + \beta)^2 * (\alpha + \beta + 1)
        }
\\
   &= \frac{
          \alpha \beta
      }{
          (\alpha + \beta)^2
          (\alpha + \beta + 1)
      }
\end{aligned}
$$

\ 


### 最頻値の計算

　最頻値は曲線(グラフ)の頂点の値であることから、$p(\phi)$を微分して、$\frac{\partial p(\phi)}{\partial \phi} = 0$となる$\phi$である。\
\

　ベータ分布の確率密度関数

$$
p(\phi)
    = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \phi^{\alpha-1}
      (1 - \phi)^{\beta-1}
$$

を$\phi$で微分する。\
\

\begin{center}\underline{\hspace{10cm}}\end{center}

【途中式の途中式】

　そのためにまずは、$\phi^{\alpha-1} (1 - \phi)^{\beta-1}$の微分について考える。\

　$\phi^{\alpha-1}$を$f(\phi)$、$(1 - \phi)^{\beta-1}$を$g(\phi)$とするとこの式の微分は、積の微分$\{f(\phi) g(\phi)\}' = f'(\phi) g(\phi) + f(\phi) g'(\phi)$である。

$$
\{\phi^{\alpha-1} (1 - \phi)^{\beta-1}\}'
    = (\phi^{\alpha-1})'
      * (1 - \phi)^{\beta-1}
      + \phi^{\alpha-1}
        * \{(1 - \phi)^{\beta-1}\}' \\
$$

　$\phi^{\alpha-1}$を微分すると$(\alpha - 1) \phi^{\alpha-2}$になる。

$$
\{\phi^{\alpha-1} (1 - \phi)^{\beta-1}\}'
    = (\alpha - 1) \phi^{\alpha-2}
      * (1 - \phi)^{\beta-1}
      + \phi^{\alpha-1}
        * \{(1 - \phi)^{\beta-1}\}' \\
$$

　$(1 - \phi)^{\beta-1}$の微分は、合成関数の微分$\{g(h(\phi))\}' = g'(h(\phi)) h'(\phi)$である。$(1 - \phi)^{\beta-1}$を$g(h(\phi))$、$1 - \phi$を$h(\phi)$とすると

$$
\begin{aligned}
\{\phi^{\alpha-1} (1 - \phi)^{\beta-1}\}'
   &= (\alpha - 1) \phi^{\alpha-2}
      * (1 - \phi)^{\beta-1}
      + \phi^{\alpha-1}
        * (\beta - 1) (1 - \phi)^{\beta-2}
        * (1 - \phi)'
\\
   &= (\alpha - 1) \phi^{\alpha-2}
      * (1 - \phi)^{\beta-1}と
      + \phi^{\alpha-1}
        * (\beta - 1) (1 - \phi)^{\beta-2}
        * (-1)
\\
   &= (\alpha - 1) \phi^{\alpha-2}
      (1 - \phi)^{\beta-1}
      - \phi^{\alpha-1}
        (\beta - 1) (1 - \phi)^{\beta-2}
\end{aligned}
$$

となる。

\begin{center}\underline{\hspace{10cm}}\end{center}

\ 

$$
\begin{aligned}
\frac{\partial p(\phi)}{\partial \phi}
   &= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \{
         (\alpha - 1) \phi^{\alpha-2}
         (1 - \phi)^{\beta-1}
         - \phi^{\alpha-1}
           (\beta - 1) (1 - \phi)^{\beta-2}
      \}
\\
   &= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \{
          (\alpha - 1) \phi^{\alpha-2}
          (1 - \phi) * (1 - \phi)^{\beta-2}
          - \phi * \phi^{\alpha-2}
            (\beta - 1) (1 - \phi)^{\beta-2}
      \}
\\
   &= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \phi^{\alpha-2} (1 - \phi)^{\beta-2}
      \{
          (1 - \phi) (\alpha - 1)
          - \phi (\beta - 1)
      \}
\end{aligned}
$$

\begin{center}\underline{\hspace{10cm}}\end{center}

【途中式の途中式】

1. $(1 - \phi)^{\beta-1} = (1 - \phi) (1 - \phi)^{\beta-2}$、$\phi^{\alpha-1} = \phi \phi^{\alpha-2}$に項を分割する。
1. $\phi^{\alpha-2}$と$(1 - \phi)^{\beta-2}$を括り出す。

\begin{center}\underline{\hspace{10cm}}\end{center}

\ 

　$\frac{\partial p(\phi)}{\partial \phi} = 0$となる$\phi$を求める。

$$
\begin{aligned}
\frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
\phi^{\alpha-2} (1 - \phi)^{\beta-2}
\{
   (1 - \phi) (\alpha - 1)
   - \phi (\beta - 1)
\}
   &= 0
\\
(1 - \phi) (\alpha - 1) - \phi (\beta - 1)
   &= 0
\\
\alpha - 1 - \alpha \phi + \phi - \beta \phi + \phi
   &= 0
\\
- (\alpha + \beta - 2) \phi
   &= - (\alpha - 1) \\
\phi
   &= \frac{\alpha - 1}{\alpha + \beta - 2}
        = \mathrm{mode}[\phi]
\end{aligned}
$$

　ここで式よりパラメータ$\alpha,\ \beta$は、$\alpha > 1,\ \beta > 1$を満たす必要がある。\
\


