---
title: "ベータ分布"
author: "@anemptyarchive\\thanks{\\url{https://www.anarchive-beta.com/}}"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  pdf_document:
    latex_engine: xelatex
    number_section: true
    toc: true
    toc_depth: 4
    keep_tex: false
header-includes:
  - \usepackage{bookmark}
  - \usepackage{xltxtra}
  - \usepackage{zxjatype}
  - \usepackage[ipa]{zxjafont}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, error = FALSE, warning = FALSE, # メッセージを非表示
  fig.align = "center", # 画像を中央揃え
  fig.width = 6, fig.height = 4.5, # 画像のサイズ
  dev = "cairo_pdf", dev.args = list(family = "ipaexg"), # {ggplot2}に日本語を組み込む場合の対処
  class.source = "numberLines lineAnchors", # ソースを番号付けする
  class.output = "numberLines lineAnchors chunkout" # 出力を番号付けする
)
```

----

【編集履歴】

- 2022/10/04：「正規化項の導出」・「統計量の導出」を修正
- 2022/10/06：「定義式」を修正

----

\newpage


# ベータ分布の定義式

　ベータ分布(Beta Distribution)の定義式を確認します。\
\


## 定義式

　ベータ分布は、パラメータ$\alpha, \beta$を用いて、次の式で定義されます。

$$
\mathrm{Beta}(\phi | \alpha, \beta)
    = \frac{
          \Gamma(\alpha + \beta)
      }{
          \Gamma(\alpha)
          \Gamma(\beta)
      }
      \phi^{\alpha-1}
      (1 - \phi)^{\beta-1}
$$

　ここで、$\Gamma(x)$はガンマ関数です。正規化項とベータ関数については「正規化項の導出」、ガンマ関数については「ガンマ関数の性質の導出」を参照してください。\
　確率変数は$0 < \phi < 1$の値をとり、2つのパラメータはそれぞれ非負の実数$\alpha > 0, \beta > 0$を満たす必要があります。\

　ベータ分布は、ベルヌーイ分布と二項分布の共役事前分布であり、$\phi$はベルヌーイ分布と二項分布のパラメータ$\phi$の条件を満たします。\
\

　ベータ分布の対数をとると、次の式になります。

$$
\begin{aligned}
\log \mathrm{Beta}(\phi | \alpha, \beta)
   &= \log \Gamma(\alpha + \beta)
      - \log \Gamma(\alpha)
      - \log \Gamma(\beta) \\
   &\quad
      + (\alpha - 1)
        \phi
      + (\beta - 1)
        \log (1 - \phi)
\end{aligned}
$$

　対数の性質より$\log x^a = a \log x$、$\log (x y) = \log x + \log y$、$\log (x y) = \log x + \log y$です。\
\


## 一様分布との関係

　2つパラメータがそれぞれ1のとき、ベータ分布は連続型の一様分布(Continuous Uniform Distribution)になります。\
\

　$\alpha = 1, \beta = 1$のときのベータ分布を考えます。ガンマ関数の性質$\Gamma(x) = (x - 1) \Gamma(x - 1)$、$\Gamma(1) = 1$、べき乗の性質$x^0 = 1$より、$\phi$の値に関わらず確率密度が1になります。

$$
\begin{aligned}
\mathrm{Beta}(\phi | \alpha = 1, \beta = 1)
   &= \frac{
          \Gamma(1 + 1)
      }{
          \Gamma(1)
          \Gamma(1)
      }
      \phi^{1-1}
      (1 - \phi)^{1-1}
\\
   &= 1
\\
   &= \frac{1}{b - a}
    = \mathrm{U}(\phi | a = 0, b = 1)
\end{aligned}
$$

　確率変数が$0 < \phi < 1$の値をとる(パラメータが$a = 0, b = 1$の)連続一様分布と一致しました。\
\


## 統計量の計算式

　ベータ分布の期待値・分散・最頻値は、それぞれ次の式で計算できます。詳しくは「統計量の導出」を参照してください。

$$
\begin{aligned}
\mathbb{E}[\phi]
   &= \frac{\alpha}{\alpha + \beta}
\\
\mathbb{V}[\phi]
   &= \frac{
          \alpha \beta
      }{
          (\alpha + \beta)^2
          (\alpha + \beta + 1)
      }
\\
\mathrm{mode}[\phi]
   &= \frac{\alpha - 1}{\alpha + \beta - 2}
    \qquad
      (\alpha > 1, \beta > 1)
\end{aligned}
$$

\ 

　この記事では、ベータ分布の定義式を確認しました。次は、正規化項を導出します。\
\


# ベータ分布の正規化項の導出

　ベータ分布(Beta Distribution)の正規化項を導出します。正規化項は、正規化係数や規格化定数(normalization constant)などとも呼ばれます。ベータ分布については「分布の定義式」を参照してください。\
\


## 定義式の確認

　まずは、ベータ分布の定義式を確認します。\
\

　ベータ分布は、ベータ関数を用いて、次の式で定義されます。

$$
\mathrm{Beta}(\phi | \alpha, \beta)
    = C_{\mathrm{Beta}}(\alpha, \beta)
      \phi^{\alpha-1}
      (1 - \phi)^{\beta-1}
$$

　ここで、$C_{\mathrm{Beta}}(\alpha, \beta)$は正規化項、$\alpha, \beta$はパラメータです。確率変数は$0 < \phi < 1$の値をとり、パラメータは$\alpha > 0, \beta > 0$を満たす必要があります。\
　また、確率分布を満たすには、確率変数がとり得る範囲で積分して1になる必要があります。

$$
\int_0^1
    \mathrm{Beta}(\phi | \alpha, \beta)
d\phi
    = 1
$$

　正規化項は、この条件を満たすための定数で、ベータ関数の逆数で定義されます。

$$
C_{\mathrm{Beta}}(\alpha, \beta)
    = \frac{
          \Gamma(\alpha + \beta)
      }{
          \Gamma(\alpha)
          \Gamma(\beta)
      }
    = \frac{1}{B(\alpha,\beta)}
$$

　$\Gamma(x)$は、ガンマ関数です。詳しくは「ガンマ関数の性質の導出」を参照してください。\
　ベータ関数は、次の式で定義されます。

$$
B(\alpha,\beta)
    = \int_0^1
          x^{\alpha-1}
          (1 - x)^{\beta-1}
      dx
$$

\ 

　ベータ関数からベータ分布の正規化項を求めます。また、ベータ関数とガンマ関数の関係を求めます。\
\


## ベータ関数の積分計算

　次は、ベータ関数の計算を行い(変形して)正規化項を導出します。\
\


### ベータ関数の性質

　ベータ関数の計算を考えます。

$$
B(\alpha,\beta)
    = \int_0^1
          x^{\alpha-1}
          (1 - x)^{\beta-1}
      dx
$$

　部分積分を行うために、前の項を変形します。微分と積分は打ち消し合うので、$f(x) = \{\int f(x) dx\}'$より

$$
\begin{aligned}
x^{\alpha-1}
   &= \left\{
          \int x^{\alpha-1} dx
      \right\}'
\\
   &= \left\{
          \frac{1}{\alpha}
          x^{\alpha}
      \right\}'
\end{aligned}
$$

で置き換えます。

$$
B(\alpha, \beta)
    = \int_0^1
          \left\{
              \frac{1}{\alpha}
              x^{\alpha}
      \right\}'
          (1 - x)^{\beta-1}
      dx
$$

　後の項を微分すると、合成関数の微分$\{g(f(x))\}' = g'(f(x)) f'(x)$より

$$
\begin{aligned}
\{(1 - x)^{\beta-1}\}'
   &= (\beta - 1) (1 - x)^{(\beta-1)-1}
      \{1 - x\}'
\\
   &= (\beta - 1) (1 - x)^{\beta-2}
      (- 1)
\\
   &= - (\beta - 1) (1 - x)^{\beta-2}
\end{aligned}
$$

となります。\
　$\frac{1}{\alpha} x^{\alpha}$を$f(x)$、$\{\frac{1}{\alpha} x^{\alpha}\}'$を$f'(x)$、$(1 - x)^{\beta-1}$を$g(x)$、$- (\beta - 1) (1 - x)^{\beta-2}$を$g'(x)$として、部分積分$\int_a^b f'(x) g(x) dx = [f(x) g(x)]_a^b - \int_a^b f(x) g'(x) dx$を行います。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \left[
          \frac{1}{\alpha} x^{\alpha}
          (1 - x)^{\beta-1}
      \right]_0^1
      - \int_0^1
          \frac{1}{\alpha} x^{\alpha}
          \Bigl\{
              - (\beta - 1) (1 - x)^{\beta-2}
          \Bigr\}
        dx
\\
   &= \left[
          \frac{1}{\alpha} x^{\alpha}
          (1 - x)^{\beta-1}
      \right]_0^1
      + \frac{\beta - 1}{\alpha}
        \int_0^1
          x^{\alpha}
          (1 - x)^{\beta-2}
        dx
\end{aligned}
$$

　$- \frac{\beta - 1}{\alpha}$は、$x$と無関係なので(積分に影響しないので)$\int$の外に出せます。\
　前の因子について、定積分$[F(x)]_a^b = F(b) - F(a)$より、$x = 0$のとき$x^a = 0$、$x = 1$のとき$1 - x = 0$なので、0となり消えます。

$$
B(\alpha, \beta)
    = 0 - 0
      + \frac{\beta - 1}{\alpha}
        \int_0^1
          x^{\alpha}
          (1 - x)^{\beta-2}
        dx
$$

　ベータ関数の定義式より、$\int$の因子を置き換えます。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \frac{\beta - 1}{\alpha}
      \int_0^1
          x^{(\alpha+1)-1}
          (1 - x)^{(\beta-1)-1}
      dx
\\
   &= \frac{\beta - 1}{\alpha}
      B(\alpha + 1, \beta - 1)
\end{aligned}
$$

　$B(\alpha, \beta) = \frac{\beta - 1}{\alpha} B(\alpha + 1, \beta - 1)$となるのが分かりました。\

　同様に、$B(\alpha + 1, \beta - 1) = \frac{\beta - 2}{\alpha + 1} B(\alpha + 2, \beta - 2)$になるので置き替えます。

$$
B(\alpha, \beta)
    = \frac{\beta - 1}{\alpha}
      \frac{\beta - 2}{\alpha + 1}
      B(\alpha + 2, \beta - 2)
\tag{1}
$$

　ここからは、$\alpha, \beta$が離散値の場合と連続値の場合に分けて進めます。どちらも同じ結果になります(が、連続値の方は諦めました)。\
\


### 離散値の場合

　先に、$\alpha, \beta$が離散値の場合を考えます。\
\

　式(1)の変形をさらに、$B(\alpha + \beta - 2, \beta - (\beta - 2)) = \frac{\beta - (\beta - 1)}{\alpha + \beta - 2} B(\alpha + \beta - 1, \beta - (\beta - 1))$まで(合計$\beta - 1$回)繰り返します。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \frac{\beta - 1}{\alpha}
      \frac{\beta - 2}{\alpha + 1}
      \cdots
      \frac{\beta - (\beta - 2)}{\alpha + \beta - 3}
      \frac{\beta - (\beta - 1)}{\alpha + \beta - 2}
      B(\alpha + \beta - 1, \beta - (\beta - 1))
\\
   &= \frac{
          (\beta - 1)
          (\beta - 2)
          \cdots
          2
          * 1
      }{
          \alpha
          (\alpha + 1)
          \cdots
          (\alpha + \beta - 3)
          (\alpha + \beta - 2)
      }
      B(\alpha + \beta - 1, 1)
\end{aligned}
$$

　最後の項について、ベータ関数の定義式より

$$
\begin{aligned}
B(\alpha + \beta - 1, 1)
   &= \int_0^1
          x^{\alpha+\beta-1-1}
          (1 - x)^{1-1}
      dx
\\
   &= \int_0^1
          x^{\alpha+\beta-2}
      dx
\end{aligned}
$$

になるので、定積分$\int_a^b f(x) dx = [F(x)]_a^b = F(b) - F(a)$を行い

$$
\begin{aligned}
B(\alpha + \beta - 1, 1)
   &= \left[
          \frac{1}{\alpha + \beta - 1}
          x^{\alpha+\beta-1}
      \right]_0^1
\\
   &= \frac{1}{\alpha + \beta - 1}
      1^{\alpha+\beta-1}
      + \frac{1}{\alpha + \beta - 1}
        0^{\alpha+\beta-1}
\\
   &= \frac{1}{\alpha + \beta - 1}
\end{aligned}
$$

で置き換えます。

$$
B(\alpha, \beta)
    = \frac{
          (\beta - 1)
          (\beta - 2)
          \cdots
          2
      }{
          \alpha
          (\alpha + 1)
          \cdots
          (\alpha + \beta - 3)
          (\alpha + \beta - 2)
      }
      \frac{1}{\alpha + \beta - 1}
$$

　分子は、1から$\beta - 1$までの自然数の積なので、$\beta - 1$の階乗$(\beta - 1)!$で表せます。また分母は、$\alpha$から$\alpha + \beta - 1$までの自然数の積なので、$(\alpha - 1)!$を掛けると$(\alpha + \beta - 1)!$になります。そこで、$\frac{(\alpha - 1)!}{(\alpha - 1)!} = 1$を掛けて項をまとめます。

$$
B(\alpha, \beta)
    = \frac{
          (\alpha - 1)!
          (\beta - 1)!
      }{
          (\alpha + \beta - 1)!
      }
$$

　ガンマ関数の性質$\Gamma(n) = (n - 1)!$より、それぞれ階乗の項をガンマ関数の項に置き換えます。

$$
B(\alpha, \beta)
    = \frac{
          \Gamma(\alpha)
          \Gamma(\beta)
      }{
          \Gamma(\alpha + \beta)
      }
$$

　ベータ関数をガンマ関数で表現できるのが分かりました。\
\


### 連続値の場合

　続いて、$\beta$が連続値の場合を考えます(未完)。\
\

　式(1)の変形をさらに、$0 < \beta - n < 1$まで(合計$n$回)繰り返します。

$$
\begin{aligned}
B(\alpha, \beta)
   &= \frac{\beta - 1}{\alpha}
      \frac{\beta - 2}{\alpha + 1}
      \cdots
      \frac{\beta - (n - 1)}{\alpha + n - 2}
      \frac{\beta - n}{\alpha + n - 1}
      B(\alpha + n, \beta - n)
\\
   &= \frac{
          (\beta - 1)
          (\beta - 2)
          \cdots
          (\beta - n + 1)
          (\beta - n)
      }{
          \alpha
          (\alpha + 1)
          \cdots
          (\alpha + n - 2)
          (\alpha + n - 1)
      }
      B(\alpha + n, \beta - n)
\end{aligned}
$$

　分子は、1から$\beta - n$までの1間隔の値の積なので、ガンマ関数の性質$\Gamma(x) = (x - 1) \Gamma(x - 1)$より、$\Gamma(\beta) = (\beta - 1) \Gamma(\beta - 1)$の変形を$\Gamma(\beta - n + 1) = (\beta - n) \Gamma(\beta - n)$まで繰り返すと$\frac{\Gamma(\beta)}{\Gamma(\beta - n)}$で表せます。また分母は、$\alpha$から$\alpha + n - 1$までの1間隔の値の積なので、$\Gamma(\alpha)$を掛けると$\Gamma(\alpha + \beta)$になります。そこで、$\frac{\Gamma(\alpha)}{\Gamma(\alpha)} = 1$を掛けて項をまとめます。

$$
\begin{aligned}
B(\alpha + n, \beta - n)
   &= \frac{
          \Gamma(\alpha)
          \Gamma(\beta)
      }{
          \Gamma(\alpha + n)
          \Gamma(\beta - n)
      }
      B(\alpha + n, \beta - n)
\end{aligned}
$$

　(証明途中にこの関係が登場するのはおかしいですがあくまで確認として、)後の項について、ベータ関数の定義式より、$B(\alpha + n, \beta - n) = \frac{\Gamma(\alpha + n) \Gamma(\beta - n)}{\Gamma(\alpha + \beta)}$で置き換えます。

$$
\begin{aligned}
B(\alpha + n, \beta - n)
   &= \frac{\Gamma(\alpha) \Gamma(\beta)}{\Gamma(\alpha + n) \Gamma(\beta - n)}
      \frac{\Gamma(\alpha + n) \Gamma(\beta - n)}{\Gamma(\alpha + \beta)}
\\
  　&= \frac{
          \Gamma(\alpha)
          \Gamma(\beta)
      }{
          \Gamma(\alpha + \beta)
      }
\end{aligned}
$$

　(今日のところはこれで納得することにしました)。\
\

　この記事では、ベータ分布の正規化項を導出しました。次は、統計量を導出します。\
\


## ベータ分布の積分計算

　ベータ関数の計算を確認できたので、ベータ分布の積分計算を考えます。\
\

　ベータ関数$B(\alpha,\beta) = \frac{\Gamma(\alpha) \Gamma(\beta)}{\Gamma(\alpha + \beta)}$の逆数$\frac{1}{B(\alpha,\beta)} = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}$を正規化項とすることで、ベータ分布の積分が1になります。

$$
\begin{aligned}
\int_0^1
    \mathrm{Beta}(\phi | \alpha, \beta)
d\phi
   &= \int_0^1
          \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
          \phi^{\alpha-1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \int_0^1
          \phi^{\alpha-1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \frac{\Gamma(\alpha) \Gamma(\beta)}{\Gamma(\alpha + \beta)}
\\
   &= 1
\end{aligned}
$$

\ 

　この記事では、ベータ分布の正規化項を導出しました。次は、統計量を導出します。\
\


# ベータ分布の統計量の導出

　ベータ分布(Beta Distribution)の統計量を導出します。ベータ分布については「分布の定義式」を参照してください。\
\


## 定義式の確認

　まずは、ベータ分布の定義式を確認します。\
\

　ベータ分布は、次の式で定義されます。

$$
\mathrm{Beta}(\phi | \alpha, \beta)
    = \frac{
          \Gamma(\alpha + \beta)
      }{
          \Gamma(\alpha)
          \Gamma(\beta)
      }
      \phi^{\alpha-1}
      (1 - \phi)^{\beta-1}
$$

　ここで、$\alpha, \beta$はパラメータ、$\Gamma(x)$はガンマ関数です。確率変数は$0 < \phi < 1$の値をとり、パラメータは$\alpha > 0, \beta > 0$を満たす必要があります。ガンマ関数については「ガンマ関数の性質の導出」を参照してください。\

　この式を用いて統計量を求めていきます。\
\


## 期待値

　連続値をとる確率分布の期待値(mean)は、確率変数がとり得る値$x$とその値の確率密度$p(x)$の積を確率変数がとり得る範囲で積分$\mathbb{E}[x] = \int x p(x) dx$して求められます。\
\

　$\phi$と$\phi$の確率密度$\mathrm{Beta}(\phi | \alpha, \beta)$の積を0から1の範囲で積分します。

$$
\begin{aligned}
\mathbb{E}[\phi]
   &= \int_0^1
          \phi
          \mathrm{Beta}(\phi | \alpha, \beta)
      d\phi
\\
   &= \int_0^1
          \phi
          \frac{
              \Gamma(\alpha + \beta)
          }{
              \Gamma(\alpha)
              \Gamma(\beta)
          }
          \phi^{\alpha-1}
          (1 - \phi)^{\beta-1}
      d\phi
\end{aligned}
$$

　$\phi^{\alpha} = \phi \phi^{\alpha-1}$で、$\phi$の項をまとめます。

$$
\mathbb{E}[\phi]
    = \int_0^1
          \frac{
              \Gamma(\alpha + \beta)
          }{
              \Gamma(\alpha)
              \Gamma(\beta)
          }
          \phi^{\alpha}
          (1 - \phi)^{\beta-1}
      d\phi
$$

　$\alpha = \alpha' - 1$とおきます。

$$
\mathbb{E}[\phi]
    = \int_0^1
          \frac{
              \Gamma(\alpha' + \beta - 1)
          }{
              \Gamma(\alpha' - 1)
              \Gamma(\beta)
          }
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
$$

　ガンマ関数の性質$\Gamma(x) = (x - 1) \Gamma(x - 1)$より、$\frac{\alpha' - 1}{\alpha' + \beta - 1} \frac{\alpha' + \beta - 1}{\alpha' - 1} = 1$を掛けて、項を変形します。

$$
\begin{aligned}
\mathbb{E}[\phi]
   &= \int_0^1
          \frac{\alpha' - 1}{\alpha' + \beta - 1}
          \frac{
              (\alpha' + \beta - 1) \Gamma(\alpha' + \beta - 1)
          }{
              (\alpha' - 1) \Gamma(\alpha' - 1)
              \Gamma(\beta)
          }
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \frac{\alpha' - 1}{\alpha' + \beta - 1}
      \int_0^1
          \frac{
              \Gamma(\alpha' + \beta)
          }{
              \Gamma(\alpha')
              \Gamma(\beta)
          }
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
\end{aligned}
$$

　$\frac{\alpha' - 1}{\alpha' + \beta - 1}$は、$\phi$と無関係なので(積分に影響しないので)$\int$の外に出せます。\
　後の因子は、パラメータが$\alpha', \beta$のベータ分布に対する$\phi$がとり得る範囲の積分なので、1になります。

$$
\begin{aligned}
\mathbb{E}[\phi]
   &= \frac{\alpha' - 1}{\alpha' + \beta - 1}
      \int_0^1
          \mathrm{Beta}(\phi | \alpha', \beta)
      d\phi
\\
   &= \frac{\alpha' - 1}{\alpha' + \beta-1}
      1
\end{aligned}
$$

　$\alpha' = \alpha + 1$で、$\alpha$に戻します。

$$
\mathbb{E}[\phi]
    = \frac{\alpha}{\alpha + \beta}
$$

　期待値の計算式が得られました。\
\


## 2乗の期待値

　分散(variance)は、「$x$の2乗の期待値」と「$x$の期待値の2乗」の差$\mathbb{V}[x] = \mathbb{E}[x^2] - (\mathbb{E}[x])^2$で求められます。そこでまずは、$\phi$の2乗の期待値を求めます。\
\

　$\phi$の2乗と$\phi$の確率密度$\mathrm{Beta}(\phi | \alpha, \beta)$の積を0から1の範囲で積分します。

$$
\begin{aligned}
\mathbb{E}[\phi^2]
   &= \int_0^1
          \phi^2
          \mathrm{Beta}(\phi | \alpha, \beta)
      d\phi
\\
   &= \int_0^1
          \phi^2
          \frac{
              \Gamma(\alpha + \beta)
          }{
              \Gamma(\alpha)
              \Gamma(\beta)
          }
          \phi^{\alpha-1}
          (1 - \phi)^{\beta-1}
      d\phi
\end{aligned}
$$

　$\phi^{\alpha+1} = \phi^2 \phi^{\alpha-1}$で、$\phi$の項をまとめます。

$$
\mathbb{E}[\phi^2]
    = \int_0^1
          \frac{
              \Gamma(\alpha + \beta)
          }{
              \Gamma(\alpha)
              \Gamma(\beta)
          }
          \phi^{\alpha+1}
          (1 - \phi)^{\beta-1}
      d\phi
$$

　$\alpha = \alpha' - 2$とおきます。

$$
\begin{aligned}
\mathbb{E}[\phi^2]
   &= \int_0^1
          \frac{
              \Gamma(\alpha' + \beta - 2)
          }{
              \Gamma(\alpha' - 2)
              \Gamma(\beta)
          }
          \phi^{(\alpha'-2)+1}
          (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \int_0^1
          \frac{
              \Gamma(\alpha' + \beta - 2)
          }{
              \Gamma(\alpha' - 2)
              \Gamma(\beta)
          }
          \phi^{\alpha'-1}
          (1 - \phi)^{\beta-1}
      d\phi
\end{aligned}
$$

　ガンマ関数の項について、$\frac{(\alpha' - 1) (\alpha' - 2)}{(\alpha' + \beta - 1) (\alpha' + \beta - 2)} \frac{(\alpha' + \beta - 1) (\alpha' + \beta - 2)}{(\alpha' - 1) (\alpha' - 2)} = 1$を掛けて変形して

$$
\begin{aligned}
\frac{
    \Gamma(\alpha' + \beta - 2)
}{
    \Gamma(\alpha - 2)
    \Gamma(\beta)
}
   &= \frac{
          (\alpha' - 1)
          (\alpha' - 2)
      }{
          (\alpha' + \beta - 1)
          (\alpha' + \beta - 2)
      }
      \frac{
          (\alpha' + \beta - 1)
          (\alpha' + \beta - 2)
          \Gamma(\alpha' + \beta - 2)
      }{
          (\alpha' - 1)
          (\alpha' - 2)
          \Gamma(\alpha - 2)
          \Gamma(\beta)
      }
\\
   &= \frac{
          (\alpha' - 1)
          (\alpha' - 2)
      }{
          (\alpha' + \beta - 1)
          (\alpha' + \beta - 2)
      }
      \frac{
          \Gamma(\alpha' + \beta)
      }{
          \Gamma(\alpha)
          \Gamma(\beta)
      }
\end{aligned}
$$

で置き換えます。

$$
\begin{aligned}
\mathbb{E}[\phi^2]
   &= \int_0^1
          \frac{
              (\alpha' - 2) (\alpha' - 1)
          }{
              (\alpha' + \beta - 2) (\alpha' + \beta - 1)
          }
          \frac{\Gamma(\alpha' + \beta)}{\Gamma(\alpha') \Gamma(\beta)}
          \phi^{\alpha'-1} (1 - \phi)^{\beta-1}
      d\phi
\\
   &= \frac{
          (\alpha' - 2) (\alpha' - 1)
      }{
          (\alpha' + \beta - 2) (\alpha' + \beta - 1)
      }
      \int_0^1
          \frac{\Gamma(\alpha' + \beta)}{\Gamma(\alpha') \Gamma(\beta)}
          \phi^{\alpha'-1} (1 - \phi)^{\beta-1}
      d\phi
\end{aligned}
$$

　後の因子は、パラメータが$\alpha', \beta$のベータ分布の積分なので、1になり消えます。

$$
\begin{aligned}
\mathbb{E}[\phi^2]
   &= \frac{
          (\alpha' - 2) (\alpha' - 1)
      }{
          (\alpha' + \beta - 2) (\alpha' + \beta - 1)
      }
      \int_0^1
          \mathrm{Beta}(\phi | \alpha', \beta)
      d\phi
\\
   &= \frac{
          (\alpha' - 2) (\alpha' - 1)
      }{
          (\alpha' + \beta - 2) (\alpha' + \beta - 1)
      }
      1
\end{aligned}
$$

　$\alpha' = \alpha + 2$で、$\alpha$に戻します。

$$
\mathbb{E}[\phi^2]
    = \frac{
          \alpha (\alpha + 1)
      }{
          (\alpha + \beta)
          (\alpha + \beta + 1)
      }
$$

　2乗の期待値が求まりました。\
\


## 分散

　$\phi^2$の期待値と$\phi$の期待値の2乗の差を求めます。

$$
\begin{aligned}
\mathbb{V}[\phi]
   &= \mathbb{E}[\phi^2]
      - (\mathbb{E}[\phi])^2
\\
   &= \frac{
          \alpha (\alpha + 1)
      }{
          (\alpha + \beta)
          (\alpha + \beta + 1)
      }
      - \left(
            \frac{\alpha}{\alpha + \beta}
      \right)^2
\end{aligned}
$$

　通分して式を整理します。

$$
\begin{aligned}
\mathbb{V}[\phi]
   &= \frac{
          \alpha (\alpha + 1)
      }{
          (\alpha + \beta)
          (\alpha + \beta + 1)
      }
      \frac{
          (\alpha + \beta)
      }{
          (\alpha + \beta)
      }
      - \frac{
            \alpha^2
        }{
            (\alpha + \beta)^2
        }
        \frac{
            (\alpha + \beta + 1)
        }{
            (\alpha + \beta + 1)
        }
\\
   &= \frac{
          \alpha^3 + \alpha^2
          + \alpha^2 \beta + \alpha \beta
      }{
          (\alpha + \beta)
          (\alpha + \beta+1)
      }
      - \frac{
            \alpha^3 + \alpha^2 \beta + \alpha^2
        }{
            (\alpha + \beta + 1)
        }
\\
   &= \frac{
          \alpha \beta
      }{
          (\alpha + \beta)^2
          (\alpha + \beta + 1)
      }
\end{aligned}
$$

　分散の計算式が得られました。\
\


## 最頻値

　連続値をとる確率分布の最頻値(mode)は、$x$についての確率密度関数$p(x)$の微分$\frac{d p(x)}{d x}$が0となる$x$です。\
\

　ベータ分布の確率密度関数$\mathrm{Beta}(\phi | \alpha, \beta)$を$\phi$で微分することを考えます。

$$
\begin{aligned}
\frac{\partial \mathrm{Beta}(\phi | \alpha, \beta)}{\partial \phi}
   &= \frac{\partial}{\partial \phi} \left\{
          \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
          \phi^{\alpha-1}
          (1 - \phi)^{\beta-1}
      \right\}
\\
   &= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \frac{\partial}{\partial \phi} \Bigl\{
          \phi^{\alpha-1}
          (1 - \phi)^{\beta-1}
      \Bigr\}
\end{aligned}
$$

　$\phi^{\alpha-1} (1 - \phi)^{\beta-1}$の微分は、積の微分$\{f(\phi) g(\phi)\}' = f'(\phi) g(\phi) + f(\phi) g'(\phi)$です。$\phi^{\alpha-1}$を$f(\phi)$、$(1 - \phi)^{\beta-1}$を$g(\phi)$として、式を変形します。

$$
\frac{\partial}{\partial \phi} \Bigl\{
    \phi^{\alpha-1}
    (1 - \phi)^{\beta-1}
\Bigr\}
    = \frac{\partial \phi^{\alpha-1}}{\partial \phi}
      (1 - \phi)^{\beta-1}
      + \phi^{\alpha-1}
        \frac{\partial (1 - \phi)^{\beta-1}}{\partial \phi}
$$

　前の項の微分は

$$
\frac{\partial \phi^{\alpha-1}}{\partial \phi}
    = (\alpha - 1) \phi^{\alpha-2}
$$

となります。\
　また後の項の微分は、合成関数の微分$\{g(h(\phi))\}' = g'(h(\phi)) h'(\phi)$です。$(1 - \phi)^{\beta-1}$を$g(h(\phi))$、$1 - \phi$を$h(\phi)$として

$$
\begin{aligned}
\frac{\partial (1 - \phi)^{\beta-1}}{\partial \phi}
   &= (\beta - 1) (1 - \phi)^{\beta-2}
      \frac{\partial (1 - \phi)}{\partial \phi}
\\
   &= (\beta - 1) (1 - \phi)^{\beta-2}
      (- 1)
\\
   &= - (\beta - 1) (1 - \phi)^{\beta-2}
\end{aligned}
$$

となります。\
　それぞれ代入して式を整理します。

$$
\begin{aligned}
\frac{\partial \mathrm{Beta}(\phi | \alpha, \beta)}{\partial \phi}
   &= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)} \Bigl\{
          (\alpha - 1)
          \phi^{\alpha-2}
          (1 - \phi)^{\beta-1}
          - (\beta - 1)
          \phi^{\alpha-1}
            (1 - \phi)^{\beta-2}
      \Bigr\}
\\
   &= \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \phi^{\alpha-2} (1 - \phi)^{\beta-2} \Bigl\{
          (\alpha - 1) (1 - \phi)
          - (\beta - 1) \phi
      \Bigr\}
\end{aligned}
$$

　ベータ分布の微分$\frac{\partial \mathrm{Beta}(\phi | \alpha, \beta)}{\partial \phi}$が求まりました。\

　$\frac{\partial \mathrm{Beta}(\phi | \alpha, \beta)}{\partial \phi}$を0とおき、$\phi$について解きます。

$$
\begin{aligned}
\frac{\partial \mathrm{Beta}(\phi | \alpha, \beta)}{\partial \phi}
   = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}
      \phi^{\alpha-2} (1 - \phi)^{\beta-2} \Bigl\{
          (\alpha - 1) (1 - \phi)
   &      - (\beta - 1) \phi
      \Bigr\}
    = 0
\\
\Rightarrow
(\alpha - 1) (1 - \phi)
- (\beta - 1) \phi
   &= 0
\\
\Rightarrow
\alpha - 1 - \alpha \phi + \phi
- \beta \phi + \phi
   &= 0
\\
\Rightarrow
(\alpha + \beta - 2) \phi
   &= \alpha - 1
\\
\Rightarrow
\phi
   &= \frac{\alpha - 1}{\alpha + \beta - 2}
    = \mathrm{mode}[\phi]
    \qquad
      (\alpha > 1)
\end{aligned}
$$

　最頻値の計算式が得られました。$0 < \phi < 1$なので、$\alpha > 1, \beta > 1$を満たす必要があります。\
\

　この記事では、ベータ分布の統計量を導出しました。\
\

