---
title: "二項分布"
author: "@anemptyarchive\\thanks{\\url{https://www.anarchive-beta.com/}}"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  pdf_document:
    latex_engine: xelatex
    number_section: true
    toc: true
    toc_depth: 4
    keep_tex: false
header-includes:
  - \usepackage{bookmark}
  - \usepackage{xltxtra}
  - \usepackage{zxjatype}
  - \usepackage[ipa]{zxjafont}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, error = FALSE, warning = FALSE, # メッセージを非表示
  fig.align = "center", # 画像を中央揃え
  fig.width = 5, fig.height = 4, # 画像のサイズ
  class.source = "numberLines lineAnchors", # ソースを番号付けする
  class.output = "numberLines lineAnchors chunkout" # 出力を番号付けする
)
```

----

【編集履歴】

- 2022/01/09：執筆開始
- 2022/02/19：初稿

----

\newpage


# 二項分布の定義式の確認

　二項分布(Binomial Distribution)の定義を確認します。\
\


## 定義式

　コインの裏表やくじの当たりはずれのように、2値をとる試行を複数回行ったときの「一方の結果となる回数」の確率分布を二項分布と言います。\
\

　試行回数を$M$、注目する方(ここでは表とします)の回数を$x$で表します。$x$は、全て裏のときの0から全て表のときの$M$までの整数になります。$x$が0から$M$の整数をとることを

$$
x \in \{0, 1, \ldots, M\}
$$

で表します。\
　裏の回数は$M - x$になります。\

　成功確率(表・当たりとなる確率)を$\phi$で表すことにします。$\phi$は、0から1の値

$$
0 < \phi < 1
$$

を満たす必要があります。$\phi$が0より大きく1より小さい値をとることを$\phi \in (0, 1)$とも表記します。\
　また、失敗確率(裏・外れとなる確率)は$1 - \phi$になります。\
\

　二項分布は、パラメータ$\phi$を用いて次の式で定義されます。

$$
\mathrm{Bin}(x | M, \phi)
    = \frac{M!}{(M - x)! x!} \phi^x (1 - \phi)^{M-x}
$$

　ここで

$$
\binom{M}{x}
    = {}_M\mathrm{C}_x
    = \frac{M!}{(M - x)! x!}
$$

は、試行回数$M$のとき表の数が$x$となる組合せの数を表します。\

　例えば、コインを3回投げて($M = 3$で)表が2回出る($x = 2$となる)とき

$$
{}_3\mathrm{C}_2
    = \frac{3!}{(3 - 2)! 2!}
    = 3
$$

となります。これは、3回中2回表となる組み合わせが「表・表・裏」「表・裏・表」「裏・表・表」の3通りであることを求めています。\

　また、$M = 3, x = 2$のとき、二項分布の式は

$$
\begin{aligned}
\mathrm{Bin}(x = 2 | M = 3, \phi)
   &= \frac{3!}{(3 - 2)! 2!}
      \phi^2
      (1 - \phi)^{3-2} \\
   &= 3 \phi^2 (1 - \phi)
\end{aligned}
$$

「3通りの組み合わせ」と「表が2回出る確率$\phi^2$」と「裏が1回出る確率$1 - \phi$」の積となります。\
　このように、$x$の値に対応した確率となるように式が定義されています。\
\

　二項分布の対数をとると

$$
\begin{aligned}
\log \mathrm{Bin}(x | N, \phi)
   &= \log N! - \log (N - x)! - \log x! \\
   &\quad
      + x \log \phi + (N - x) \log (1 - \phi)
\end{aligned}
$$

となります。対数の性質より$\log x^a = a \log x$、$\log (x y) = \log x + \log y$です。\
\


## 他の分布との関係

　試行回数が1回($M = 1$)のとき、二項分布は

$$
\begin{aligned}
\mathrm{Bin}(x | 1, \phi)
   &= \frac{1!}{(1 - x)! x!}
      \phi^x
      (1 - \phi)^{1-x} \\
   &= \frac{1!}{1! 0!}
      \phi^x
      (1 - \phi)^{1-x} \\
   &= \phi^x
      (1 - \phi)^{1-x}
          = \mathrm{Bern}(x | \phi)
\end{aligned}
$$

ベルヌーイ分布と等しくなります。階乗の定義より$0! = 1$なので、$x$が0か1のどちらであっても組み合わせの項は1になります。\
　ベルヌーイ分布は、コインを1回投げて表が1回出ることを$x = 1$、表が1回も出ない(裏が出る)ことを$x = 0$で表していると言えます。\

　つまり、ベルヌーイ分布は二項分布の特殊な形であると言えます。逆に、二項分布はベルヌーイ分布を拡張(多試行化)した形と言えます。\
\


## 統計量の計算式

　二項分布の平均と分散は、次の式で計算できます。詳しくは「統計量の導出」を参照してください。

$$
\begin{aligned}
\mathbb{E}[x]
   &= M \phi
\\
\mathbb{V}[x]
   &= M \phi (1 - \phi)
\end{aligned}
$$

　$M, \phi$が大きいほど平均が大きくなります。\
　$M$が大きいまたは$\phi$が0.5に近いほど分散が大きくなります。\

　試行回数が$M = 1$のとき、ベルヌーイ分布の平均・分散と一致します。\
\


# 二項分布の定義式の導出

　二項分布(Binomial Distribution)の定義式を導出します。\
\


# 二項分布のモーメント母関数の導出

　二項分布(Binomial Distribution)のモーメント母関数(積率母関数)を導出します。二項分布については「定義式の確認」を参照してください。\
\

　モーメント母関数は、$e^{tx}$の期待値として定義されます。$e$はネイピア数です。

$$
\begin{aligned}
M(t)
   &= \mathbb{E}[e^{tx}]
\\
   &= \sum_{x=0}^M
          e^{tx}
          \mathrm{Bin}(x | M, \phi)
\\
   &= \sum_{x=0}^M
          e^{tx}
          {}_MC_x \phi^x (1 - \phi)^{M-x}
\end{aligned}
$$

　ここで、$\mathrm{Bin}(x | M, \phi)$は二項分布を表し、$x$は成功回数、$M$は試行回数、$\phi$は成功確率です。\
　$e^{tx} = (e^t)^x$と$\phi^x$をまとめます。

$$
M(t)
    = \sum_{x=0}^M
          {}_MC_x (\phi e^t)^x (1 - \phi)^{M-x}
$$

　二項定理$(a + b)^n = \sum_{r=0}^n {}_nC_r a^r b^{n-r}$の形をしているので、右辺から左辺の式に変形します。

$$
M(t)
    = (\phi e^t + 1 - \phi)^M
$$

　モーメント母関数が得られました。\
\


# 二項分布の特性関数の導出

　二項分布(Binomial Distribution)の特性関数を導出します。二項分布については「定義式の確認」を参照してください。\
\

　特性関数は、$e^{itx}$の期待値として定義されます。$e$はネイピア数、$i$は虚数単位です。

$$
\begin{aligned}
\varphi(t)
   &= \mathbb{E}[e^{itx}]
\\
   &= \sum_{x=0}^M
          e^{itx}
          \mathrm{Bin}(x | M, \phi)
\\
   &= \sum_{x=0}^M
          e^{itx}
          {}_MC_x \phi^x (1 - \phi)^{M-x}
\end{aligned}
$$

　ここで、$\mathrm{Bin}(x | M, \phi)$は二項分布を表し、$x$は成功回数、$M$は試行回数、$\phi$は成功確率です。\
　$e^{itx} = (e^{it})^x$と$\phi^x$をまとめます。

$$
\varphi(t)
    = \sum_{x=0}^M
          {}_MC_x (\phi e^{it})^x (1 - \phi)^{M-x}
$$

　二項定理$(a + b)^n = \sum_{r=0}^n {}_nC_r a^r b^{n-r}$の形をしているので、右辺から左辺の式に変形します。

$$
\varphi(t)
    = (\phi e^{it} + 1 - \phi)^M
$$

　特性関数が得られました。モーメント母関数の$t$を$it$に置き換えた式と一致します。\
\


# 二項分布の統計量の導出

　二項分布(Binomial Distribution)の平均(期待値)と分散を導出します。二項分布については「定義式の確認」を参照してください。\
\


## 定義式から導出

　定義式を利用して、平均と分散の計算式を導出します。\

　二項分布は、次の式で定義されます。

$$
\mathrm{Bin}(x | M, \phi)
    = \frac{M!}{(M - x)! x!} \phi^x (1 - \phi)^{M-x}
$$

　ここで、$x$は成功回数、$M$は試行回数、$\phi$は成功確率です。\
　確率変数の値$x$は、$x \in \{0, 1, \cdots, M\}$となります。パラメータ$\phi$は、$\phi \in (0, 1)$を満たす必要があります。また、失敗回数は$M - x$、失敗確率は$1 - \phi$で表せます。
\

　二項分布の平均と分散は、次の式で計算できます。

$$
\begin{aligned}
\mathbb{E}[x]
   &= M \phi
\\
\mathbb{V}[x]
   &= M \phi (1 - \phi)
\end{aligned}
$$

　試行回数が$M = 1$のとき、ベルヌーイ分布の平均・分散と一致します。\

　定義式を用いて、平均と分散の計算式を導出します。\
\


### 平均の計算

　二項分布の平均を導出します。

$$
\begin{aligned}
\mathbb{E}[x]
  &= \sum_{x=0}^M
          x
          \mathrm{Bin}(x | M, \phi)
\\
   &= \sum_{x=0}^M
          x
          {}_MC_x \phi^x (1 - \phi)^{M-x}
\end{aligned}
$$

　$x = 0$について、0になり計算結果に影響しないので、$\sum_{x=0}^M$から取り出します。

$$
\begin{aligned}
\mathbb{E}[x]
   &= 0
      {}_MC_0 \phi^0 (1 - \phi)^{M-0}
      + \sum_{x=1}^M
          x
          {}_MC_x \phi^x (1 - \phi)^{M-x}
\\
   &= \sum_{x=1}^M
          x
          {}_MC_x \phi^x (1 - \phi)^{M-x}
\end{aligned}
$$

　組み合わせの項について

$$
{}_MC_x
    = \frac{M!}{(M - x)! x!}
    = \frac{M}{x}
      \frac{(M - 1)!}{\{(M - 1) - (x - 1)\}! (x - 1)!}
    = \frac{M}{x} {}_{M-1}C_{x-1}
$$

と変形します。

$$
\begin{aligned}
\mathbb{E}[x]
   &= \sum_{x=1}^M
          x \frac{M}{x}
          {}_{M-1}C_{x-1} \phi^x (1 - \phi)^{M-x}
\\
   &= M
      \sum_{x=1}^M
          {}_{M-1}C_{x-1} \phi^x (1 - \phi)^{M-x}
\end{aligned}
$$

　総和について$\sum_{x=1}^M = \sum_{x-1=0}^{M-1}$、$1 - \phi$の指数について$M - x = (M - 1) - (x - 1)$と変形して、さらに$x' = x - 1$、$M' = M - 1$に置き換えます。

$$
\begin{aligned}
\mathbb{E}[x]
   &= M
      \sum_{x-1=0}^{M-1}
          {}_{M-1}C_{x-1} \phi^x (1 - \phi)^{(M-1)-(x-1)}
\\
   &= M
      \sum_{x'=0}^{M'}
          {}_{M'}C_{x'} \phi^{x'+1} (1 - \phi)^{M'-x'}
\end{aligned}
$$

　$\phi^{x+1} = \phi \phi^x$に分割します。

$$
\mathbb{E}[x]
    = M \phi
      \sum_{x'=0}^{M'}
          {}_{M'}C_{x'} \phi^{x'} (1 - \phi)^{M'-x'}
\tag{1}
$$

　式(1)は二項定理$(a + b)^n = \sum_{r=0}^n {}_nC_r a^r b^{n-r}$の形をしているので、右辺から左辺の式に変形します。

$$
\begin{aligned}
\mathbb{E}[x]
   &= M \phi
      \Bigl\{
          \phi + (1 - \phi)
      \Bigr\}^{M'}
\\
   &= M \phi
\end{aligned}
$$

　平均の計算式が得られました。\

　次のようにも解釈できます。式(1)は試行回数$M'$・パラメータ$\phi$の二項分布になっています。

$$
\mathbb{E}[x]
    = M \phi
      \sum_{x'=0}^{M'}
          \mathrm{Bin}(x' | M', \phi)
$$

　全事象$x' = 0, 1, \ldots, M'$の和なので1になります。

$$
\mathbb{E}[x]
    = M \phi
$$

　先ほどの結果と一致しました。\
\


### 二乗の平均の計算

　続いて、$x^2$の平均を求めます。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= \sum_{x=0}^M
          x^2
          \mathrm{Bin}(x | M, \phi)
\\
   &= \sum_{x=0}^M
          x^2
          {}_MC_x \phi^x (1 - \phi)^{M-x}
\end{aligned}
$$

　$x^2 = x (x - 1) + x$に分割します。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= \sum_{x=0}^M
          \{x (x - 1) + x\}
          {}_MC_x \phi^x (1 - \phi)^{M-x}
\\
   &= \sum_{x=0}^M
          x (x - 1)
          {}_MC_x \phi^x (1 - \phi)^{M-x}
      + \sum_{x=0}^M
          x
          {}_MC_x \phi^x (1 - \phi)^{M-x}
\end{aligned}
$$

　前の項に関して、$x = 0, 1$は0になるので取り出します。後の項は、$x$の平均なので置き換えます。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= 0 (0 - 1)
          {}_MC_0 \phi^0 (1 - \phi)^{M-0} \\
   &\quad
      + 1 (1 - 1)
          {}_MC_1 \phi^1 (1 - \phi)^{M-1} \\
   &\quad
      + \sum_{x=2}^M
          x (x - 1)
          {}_MC_x \phi^x (1 - \phi)^{M-x} \\
   &\quad
      + \mathbb{E}[x]
\\
   &= \sum_{x=2}^M
          x (x - 1)
          {}_MC_x \phi^x (1 - \phi)^{M-x}
      + M \phi
\end{aligned}
$$

　組み合わせの項について

$$
{}_MC_x
    = \frac{M!}{(M - x)! x!}
    = \frac{M (M - 1)}{x (x - 1)}
      \frac{(M - 2)!}{\{(M - 2) - (x - 2)\}! (x - 2)!}
    = \frac{M (M - 1)}{x (x - 1)}
      {}_{M-2}C_{x-2}
$$

と変形します。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= \sum_{x=2}^M
          x (x - 1)
          \frac{M (M - 1)}{x (x - 1)}
          {}_{M-2}C_{x-2} \phi^x (1 - \phi)^{M-x}
      + M \phi
\\
   &= M (M - 1)
      \sum_{x=2}^M
          {}_{M-2}C_{x-2} \phi^x (1 - \phi)^{M-x}
      + M \phi
\end{aligned}
$$

　総和について$\sum_{x=2}^M = \sum_{x-2=0}^{M-2}$、$1 - \phi$の指数について$M - x = (M - 2) - (x - 2)$と変形して、さらに$x' = x - 2$、$M' = M - 2$に置き換えます。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= M (M - 1)
      \sum_{x-2=0}^{M-2}
          {}_{M-2}C_{x-2} \phi^x (1 - \phi)^{(M-2)-(x-2)}
      + M \phi
\\
   &= M (M - 1)
      \sum_{x'=0}^{M'}
          {}_{M'}C_{x'} \phi^{x'+2} (1 - \phi)^{M'-x'}
      + M \phi
\end{aligned}
$$

　$\phi^{x'+2} = \phi^2 \phi^{x'}$に分割します。

$$
\mathbb{E}[x^2]
    = M (M - 1) \phi^2
      \sum_{x'=0}^{M'}
          {}_{M'}C_{x'} \phi^{x'} (1 - \phi)^{M'-x'}
      + M \phi
\tag{2}
$$

　二項定理$(a + b)^n = \sum_{r=0}^n {}_nC_r a^r b^{n-r}$の変形を行います。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= M (M - 1) \phi^2
      \Bigl\{
          \phi + (1 - \phi)
      \Bigr\}^{M'}
      + M \phi
\\
   &= M (M - 1) \phi^2
      + M \phi
\end{aligned}
$$

　二乗の平均が求まりました。\

　あるいは、式(2)を試行回数$M'$・パラメータ$\phi$の二項分布の全事象の和と考えても同じ結果が得られます。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= M (M - 1) \phi^2
      \sum_{x'=0}^{M'}
          \mathrm{Bin}(x' | M', \phi)
      + M \phi
\\
   &= M (M - 1) \phi^2
      + M \phi
\end{aligned}
$$

\ 


### 分散の計算

　分散は「$x$の2乗の平均」と「$x$の平均の2乗」の差で求められます。

$$
\begin{aligned}
\mathbb{V}[x]
   &= \mathbb{E}[x^2]
      - (\mathbb{E}[x])^2
\\
   &= M (M - 1) \phi^2
      + M \phi
      - (M \phi)^2
\end{aligned}
$$

　括弧を展開して、式を整理します。

$$
\begin{aligned}
\mathbb{V}[x]
   &= M^2 \phi^2 - M \phi^2
      + M \phi
      - M^2 \phi^2
\\
   &= M \phi (1 - \phi)
\end{aligned}
$$

　分散の計算式が得られました。\
\


## モーメント母関数から導出

　モーメント母関数(積率母関数)を利用して、平均と分散の計算式を導出します。\

　二項分布のモーメント母関数は、次の式になります。詳しくは「モーメント母関数の導出」を参照してください。

$$
M(t)
    = (\phi e^t + 1 - \phi)^M
$$

　ここで、$\phi, M$は二項分布のパラメータで成功確率と試行回数、$e$はネイピア数です。\

　二項分布の平均と分散は、次の式で計算できます。

$$
\begin{aligned}
\mathbb{E}[x]
   &= M \phi
\\
\mathbb{V}[x]
   &= M \phi (1 - \phi)
\end{aligned}
$$

　試行回数が$M = 1$のとき、ベルヌーイ分布の平均・分散と一致します。\

　モーメント母関数の微分を用いて、平均と分散の計算式を導出します。\
\


### モーメント母関数の1階微分の計算

　モーメント母関数を$t$に関して微分します。

$$
\frac{d M(t)}{d t}
    = \frac{d}{d t} \Bigl\{
          (\phi e^t + 1 - \phi)^M
      \Bigr\}
$$

　式全体を$g(f(x))$、丸括弧を$f(x)$として、合成関数の微分$\frac{d g(f(x))}{d x} = \frac{d g(x)}{d f(x)} \frac{d f(x)}{d x}$を行います。

$$
\begin{aligned}
\frac{d M(t)}{d t}
   &= M (\phi e^t + 1 - \phi)^{M-1}
      \frac{d}{d t} \Bigl\{
          \phi e^t + 1 - \phi
      \Bigr\}
\\
   &= M (\phi e^t + 1 - \phi)^{M-1}
      \phi e^t
\end{aligned}
$$

　指数関数の微分は$\frac{d e^x}{d x} = e^x$です。\
　式を整理します。

$$
\frac{d M(t)}{d t}
    = M \phi e^t
      (\phi e^t + 1 - \phi)^{M-1}
$$

　1階微分が求まりました。\
\


### モーメント母関数の2階微分の計算

　続いて、モーメント母関数を$t$に関して2階微分します。1階微分$\frac{d M(t)}{d t}$を更に微分します。

$$
\begin{aligned}
\frac{d^2 M(t)}{d t^2}
   &= \frac{d}{d t} \frac{d M(t)}{d t} 
\\
   &= \frac{d}{d t} \Bigl\{
          M \phi e^t
          (\phi e^t + 1 - \phi)^{M-1}
      \Bigr\}
\end{aligned}
$$

　$t$に関する項を2つ含むので、積の微分$\frac{d f(x) g(x)}{d x} = \frac{d f(x)}{d x} g(x) + f(x) \frac{d g(x)}{d x}$を行います。

$$
\frac{d^2 M(t)}{d t^2}
    = \frac{d}{d t} \Bigl\{
          M \phi e^t
      \Bigr\}
      (\phi e^t + 1 - \phi)^{M-1}
      + M \phi e^t
        \frac{d}{d t} \Bigl\{
          (\phi e^t + 1 - \phi)^{M-1}
        \Bigr\}
$$

　前の項は指数関数の微分、後の項は合成関数の微分になります。

$$
\begin{aligned}
\frac{d^2 M(t)}{d t^2}
    &= M \phi e^t
      (\phi e^t + 1 - \phi)^{M-1}
      + M \phi e^t
        (M - 1)
        (\phi e^t + 1 - \phi)^{M-2}
        \frac{d}{d t} \Bigl\{
          \phi e^t + 1 - \phi
        \Bigr\}
\\
   &= M \phi e^t
      (\phi e^t + 1 - \phi)^{M-1}
      + M \phi e^t
        (M - 1)
        (\phi e^t + 1 - \phi)^{M-2}
        \phi e^t
\end{aligned}
$$

　式を整理します。

$$
\frac{d^2 M(t)}{d t^2}
    = M \phi e^t
      (\phi e^t + 1 - \phi)^{M-1}
      + M (M - 1) \phi^2 e^{2t}
        (\phi e^t + 1 - \phi)^{M-2}
$$

　2階微分が求まりました。\
\


### 平均の計算

　モーメント母関数の微分に$t = 0$を代入すると、平均が得られます。

$$
\begin{aligned}
\mathbb{E}[x]
   &= \frac{d M(0)}{d t}
\\
   &= M \phi e^0
      (\phi e^0 + 1 - \phi)^{M-1}
\\
   &= M \phi
\end{aligned}
$$

　0乗は$x^0 = 1$です。\
\


### 二乗の平均の計算

　同様に、モーメント母関数の2階微分に$t = 0$を代入すると、二乗の平均が得られます。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= \frac{d^2 M(0)}{d t^2}
\\
   &= M \phi e^0
      (\phi e^0 + 1 - \phi)^{M-1}
      + M \phi e^0
        (M - 1)
        (\phi e^0 + 1 - \phi)^{M-2}
        \phi e^0
\\
   &= M \phi
      + M (M - 1)
        \phi^2
\end{aligned}
$$

\ 


### 分散の計算

　分散は「$x$の2乗の平均」と「$x$の平均の2乗」の差で求められます。

$$
\begin{aligned}
\mathbb{V}[x]
   &= \mathbb{E}[x^2]
      - (\mathbb{E}[x])^2
\\
   &= M (M - 1) \phi^2
      + M \phi
      - (M \phi)^2
\end{aligned}
$$

　括弧を展開して、式を整理します。

$$
\begin{aligned}
\mathbb{V}[x]
   &= M^2 \phi^2 - M \phi^2
      + M \phi
      - M^2 \phi^2
\\
   &= M \phi (1 - \phi)
\end{aligned}
$$

　分散の計算式が得られました。\
\


## 特性関数から導出

　特性関数を利用して、平均と分散の計算式を導出します。\

　二項分布の特性関数は、次の式になります。詳しくは「特性関数の導出」を参照してください。

$$
\varphi(t)
    = (\phi e^{it} + 1 - \phi)^M
$$

　ここで、$\phi, M$は二項分布のパラメータで成功確率と試行回数、$e$はネイピア数、$i$は虚数単位です。\

　二項分布の平均と分散は、次の式で計算できます。

$$
\begin{aligned}
\mathbb{E}[x]
   &= M \phi
\\
\mathbb{V}[x]
   &= M \phi (1 - \phi)
\end{aligned}
$$

　試行回数が$M = 1$のとき、ベルヌーイ分布の平均・分散と一致します。\

　特性関数の微分を用いて、平均と分散の計算式を導出します。\
\


### 特性関数の1階微分の計算

　特性関数を$t$に関して微分します。

$$
\frac{d \varphi(t)}{d t}
    = \frac{d}{d t} \Bigl\{
          (\phi e^{it} + 1 - \phi)^M
      \Bigr\}
$$

　式全体を$g(f(x))$、丸括弧を$f(x)$として、合成関数の微分$\frac{d g(f(x))}{d x} = \frac{d g(x)}{d f(x)} \frac{d f(x)}{d x}$を行います。

$$
\begin{aligned}
\frac{d \varphi(t)}{d t}
   &= M (\phi e^{it} + 1 - \phi)^{M-1}
      \frac{d}{d t} \Bigl\{
          \phi e^{it} + 1 - \phi
      \Bigr\}
\\
   &= M (\phi e^{it} + 1 - \phi)^{M-1}
      \phi e^{it}
      \frac{d it}{d t}
\\
   &= M (\phi e^{it} + 1 - \phi)^{M-1}
      \phi e^{it} i
\end{aligned}
$$

　指数に係数を含む指数関数の微分は$\frac{d e^{ax}}{d x} = e^{ax} \frac{d ax}{d x} = a e^{ax}$です。\
　式を整理します。

$$
\frac{d \varphi(t)}{d t}
    = i M \phi e^{it}
      (\phi e^{it} + 1 - \phi)^{M-1}
$$

　1階微分が求まりました。\
\


### 特性関数の2階微分の計算

　続いて、特性関数を$t$に関して2階微分します。1階微分$\frac{d \varphi(t)}{d t}$を更に微分します。

$$
\begin{aligned}
\frac{d^2 \varphi(t)}{d t^2}
   &= \frac{d}{d t} \frac{d \varphi(t)}{d t} 
\\
   &= \frac{d}{d t} \Bigl\{
          i M \phi e^{it}
          (\phi e^{it} + 1 - \phi)^{M-1}
      \Bigr\}
\end{aligned}
$$

　$t$に関する項を2つ含むので、積の微分$\frac{d f(x) g(x)}{d x} = \frac{d f(x)}{d x} g(x) + f(x) \frac{d g(x)}{d x}$を行います。

$$
\frac{d^2 \varphi(t)}{d t^2}
    = \frac{d}{d t} \Bigl\{
          i M \phi e^{it}
      \Bigr\}
      (\phi e^{it} + 1 - \phi)^{M-1}
      + i M \phi e^{it}
        \frac{d}{d t} \Bigl\{
          (\phi e^{it} + 1 - \phi)^{M-1}
        \Bigr\}
$$

　前の項は指数関数の微分、後の項は合成関数の微分になります。

$$
\begin{aligned}
\frac{d^2 \varphi(t)}{d t^2}
   &= i M \phi e^{it}
      \frac{d it}{d t}
      (\phi e^{it} + 1 - \phi)^{M-1}
      + i M \phi e^{it}
        (M - 1)
        (\phi e^{it} + 1 - \phi)^{M-2}
        \frac{d}{d t} \Bigl\{
          \phi e^{it} + 1 - \phi
        \Bigr\}
\\
   &= i M \phi e^{it} i
        (\phi e^{it} + 1 - \phi)^{M-1}
      + i M \phi e^{it}
        (M - 1)
        (\phi e^{it} + 1 - \phi)^{M-2}
        \phi e^{it}
        \frac{d it}{d t}
\\
   &= i^2 M \phi e^{it}
        (\phi e^{it} + 1 - \phi)^{M-1}
      + i M \phi e^{it}
        (M - 1)
        (\phi e^{it} + 1 - \phi)^{M-2}
        \phi e^{it} i
\end{aligned}
$$

　虚数単位の2乗は$i^2 = -1$です。

$$
\frac{d^2 \varphi(t)}{d t^2}
    = -  M \phi e^{it}
        (\phi e^{it} + 1 - \phi)^{M-1}
      - M (M - 1) \phi^2 e^{2it}
        (\phi e^{it} + 1 - \phi)^{M-2}
$$

　2階微分が求まりました。\
\


### 平均の計算

　特性関数の微分に$t = 0$を代入し、$i$の逆数を掛けると、平均が得られます。

$$
\begin{aligned}
\mathbb{E}[x]
   &= \frac{1}{i}
      \frac{d \varphi(0)}{d t}
\\
   &= \frac{1}{i}
      i M (\phi e^{0} + 1 - \phi)^{M-1}
      \phi e^{0}
\\
   &= M \phi
\end{aligned}
$$

　0乗は$x^0 = 1$です。\
\


### 二乗の平均の計算

　同様に、特性関数の2階微分に$t = 0$を代入し、$i$の2乗の逆数を掛けると、二乗の平均が得られます。

$$
\begin{aligned}
\mathbb{E}[x^2]
   &= \frac{1}{i^2}
      \frac{d^2 \varphi(0)}{d t^2}
\\
   &= \frac{1}{-1} \Bigl\{
          - M \phi e^{0}
            (\phi e^{0} + 1 - \phi)^{M-1}
          - M (M - 1) \phi^2 e^{0}
            (\phi e^{0} + 1 - \phi)^{M-2}
      \Bigr\}
\\
   &= M \phi
      + M (M - 1)
        \phi^2
\end{aligned}
$$

\ 


### 分散の計算

　分散は「$x$の2乗の平均」と「$x$の平均の2乗」の差で求められます。

$$
\begin{aligned}
\mathbb{V}[x]
   &= \mathbb{E}[x^2]
      - (\mathbb{E}[x])^2
\\
   &= M (M - 1) \phi^2
      + M \phi
      - (M \phi)^2
\end{aligned}
$$

　括弧を展開して、式を整理します。

$$
\begin{aligned}
\mathbb{V}[x]
   &= M^2 \phi^2 - M \phi^2
      + M \phi
      - M^2 \phi^2
\\
   &= M \phi (1 - \phi)
\end{aligned}
$$

　分散の計算式が得られました。\
\


# 参考書籍{-}

- 岩田具治『トピックモデル』(機械学習プロフェッショナルシリーズ)講談社,2015年.
- 須山敦志『ベイズ推論による機械学習入門』(機械学習スタートアップシリーズ)杉山将監修,講談社,2017年.
- C.M.ビショップ著,元田 浩・他訳『パターン認識と機械学習 上』丸善出版,2012年.
- 星野満博・西崎雅仁『数理統計の探求』晃洋書房,2012年.


